options:
  storage-persist:
    description: |
      Do not store profiles in memory, persist to disk. Location for persistence is '/var/lib/parca'
    type: boolean
    default: false

  memory-storage-limit:
    description: |
      When storing profiles in memory, configure the in-memory storage limit, specified in MB.

      Does nothing if storage-persist is True.
    type: int
    default: 4096
